<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VivantValley</AssemblyName>
    <RootNamespace>VivantValley</RootNamespace>
    <Version>0.14.2</Version>
    <DebugType>portable</DebugType>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GamePath Condition="'$(GamePath)' == ''">E:\SteamLibrary\steamapps\common\Stardew Valley</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="StardewModdingAPI" HintPath="$(GamePath)\StardewModdingAPI.dll" Private="false" />
    <Reference Include="Stardew Valley" HintPath="$(GamePath)\Stardew Valley.dll" Private="false" />
    <Reference Include="StardewValley.GameData" HintPath="$(GamePath)\StardewValley.GameData.dll" Private="false" />
    <Reference Include="MonoGame.Framework" HintPath="$(GamePath)\MonoGame.Framework.dll" Private="false" />
    <Reference Include="xTile" HintPath="$(GamePath)\xTile.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(GamePath)\smapi-internal\0Harmony.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Update="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="i18n\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="assets\social\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="assets\stories\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
